### ISSUE TITLE
Density dygraph problems

### ISSUE THREAD

**Issue by cestes-19** [cestes-19/rvc18#1]
Line 834 for rvc18/big_csv/RVC_99_18_2.rmd will not let me use 'select'(or filter) to subset through the 'files' I am graphing (files are the 13 csvs with density data). I am trying to knit the data, but I get this error each time. 

Error in select(YEAR, protected_status, SPECIES_CD, density) :  object 'YEAR' not found

Any suggestions or ideas? @bbest @eqmh

![Screenshot (59)](https://user-images.githubusercontent.com/42186653/84693585-b9869380-af15-11ea-8a18-49172c87cb3e.png)

**Comment by 7yl4r** [comment]
My guess here is that the parser is interpreting `YEAR` as a variable when it is actually a raw string.
Maybe try putting quotes around the column names?

```
select("YEAR", "protected_status", "SPECIES_CD", "density")
```

**Comment by cestes-19** [comment]
That gives me a different error

Error in UseMethod("select_") : no applicable method for 'select_' applied to an object of class "character"
